on:
  push

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if the commit message contains "conditions"
        id: check_message
        run:  |
          if [[ "${{github.event.head_commit.message}}" == *"condition"* ]]; then
            # statement
            echo Condition matches
          else
            # statement
            echo Condition does not match
          fi

  conditional_job:
    runs-on: ubuntu-latest
      if $message == *"condition"*; then
        echo All good
      else
        echo Not Good
      fi
