My Test Workflow
on:
  push

job:
  display_output:
      name: Run a simple command
      runs-on: ubuntu-latest
      steps:
        - name: Display the output
          run: |
            echo "This is my first workflow"
          shell: bash
          
