on:
  workflow_call:
   inputs:
     message:
       required: true
       typoep: string

jobs:
  job_for_main:
    runs-on: ubuntu-latest
    steps:
      - name: Display the output on main workflow
        run: echo "this is a message called from reusable workfloe - ${{ inputs.message }}"
      
