name: A variable Test
on:
  push

env:
  DAY_OF_WEEK: Monday
  TopLevel_msg:  "${{github.event.head_commit.message}}"

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: LaMonte

  Cond_check:
    runs-on: ubuntu-latest
    env:
      Stat: "${{github.event.head_commit.message}}"
      bStat: contains(github.event.head_commit.message, 'Wonderful')
    steps:
      - name: What I am doing
        run: echo "{{$Stat}} {{$TopLevel_msg}}"
        run: echo bStat


#if [[ "${{github.event.head_commit.message}}" == *"condition"* ]]; then
