on:
  push
  
permissions:
  pull-requests: write
  contents: write
  repository-projects: write

  
jobs:
  job1-display_output:
    name: Display a file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Job1-Display the output of the file
        run: |
          cat test.txt
        shell: bash

  job2-display_output:
    name: Display a file
    runs-on: ubuntu-latest
    #needs: job1-display_output
    env:
      name: "LaMonte"
    steps:
      - name: Job2-Display the output of the file
        run: |
         echo "this is name $name"
        shell: bash
