on:
  push
  
permissions:
  pull-requests: write
  contents: write
  repository-projects: write

  
jobs:
  job1-display_output:
    name: Display a file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Job1-Display the output of the file
        run: |
          cat test.txt
        shell: bash

      - name: Output for job 2
        id: myoutput
        run:  |
            echo "::set-output name=mystring::This is job1 output"
    outputs:
      job1_output: ${{ steps.myoutput.outputs.mystring }}

  job2-display_output:
    name: Display a file
    runs-on: ubuntu-latest
    needs: job1-display_output
    environment: course
    env:
      name: "LaMonte"
    steps:
      - name: Job2-Display the output of the file
        run: |
         echo "this is name $name"
         echo "this is from ${{ vars.topic }}"
         echo "Testing my ${{secrets.TestSecret}}"
         echo "This is job2.  The output is coming from job1 - ${{ needs.job1-display_output.outputs.job1_output}}"
        shell: bash
    call-reusable-workflow:
      uses: ./,github/workflows/reusable-workflow.yml
      with:
        message: "this is main workflow"

